theme: jekyll-theme-minimal

title: Global Biodiversity Decline & What You Can Do
description: Final project website for Foundation Biology at Olin College, Fall 2020

logo: "logo.JPG"
show_downloads: "false"

